import { GoogleGenAI, Modality } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

// Helper function to parse data URL more robustly
const parseDataUrl = (dataUrl: string): { mimeType: string; data: string } | null => {
    const match = dataUrl.match(/^data:(image\/(?:jpeg|png|webp));base64,(.*)$/);
    if (match && match[1] && match[2]) {
        return {
            mimeType: match[1],
            data: match[2],
        };
    }
    return null;
}

export const generatePortrait = async (
  faceImageDataUrl: string,
  hoodieImageDataUrl: string,
  customPrompt: string,
): Promise<string> => {
  try {
    const faceImageDetails = parseDataUrl(faceImageDataUrl);
    const hoodieImageDetails = parseDataUrl(hoodieImageDataUrl);

    if (!faceImageDetails) {
      throw new Error("Invalid face image format. Please upload a valid JPG, PNG, or WEBP file.");
    }
    if (!hoodieImageDetails) {
      throw new Error("Invalid hoodie image format. Please upload a valid JPG, PNG, or WEBP file.");
    }

    const faceImagePart = {
      inlineData: {
        mimeType: faceImageDetails.mimeType,
        data: faceImageDetails.data,
      },
    };

    const hoodieImagePart = {
      inlineData: {
        mimeType: hoodieImageDetails.mimeType,
        data: hoodieImageDetails.data,
      },
    };

    const textPrompt = `Using the person's face from the first image and the hoodie from the second image, generate a photorealistic, professional headshot suitable for a corporate profile. The final image should seamlessly blend the person's face onto a body wearing the hoodie, maintaining a natural look and proportions. The background should be a simple, modern, slightly out-of-focus office setting. The lighting should be professional and flattering. ${customPrompt}`;

    const textPart = {
        text: textPrompt,
    };
    
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          faceImagePart,
          hoodieImagePart,
          textPart,
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        const base64ImageBytes: string = part.inlineData.data;
        return `data:image/png;base64,${base64ImageBytes}`;
      }
    }
    
    throw new Error('No image was generated by the API.');

  } catch (error) {
    console.error("Error generating portrait with Gemini:", error);
    if (error instanceof Error) {
        return Promise.reject(error.message);
    }
    return Promise.reject("An unknown error occurred during image generation.");
  }
};